[project]
name = "eventfetcher"
version = "1.3.0"
description = "A project to fetch events"
authors = [
    { name = "Marc Grunberg", email = "marc.grunberg@unistra.fr" }
]
dependencies = [
    "icecream>=2.1.5",
    "obspy @ git+https://github.com/marcopovitch/obspy-libmseed-threadsafe@3dc5d4942",
    "pandas>=2.3.1",
    "pyyaml",
    "seisbench>=0.9.1",
]

[project.scripts]
eventfetcher = "eventfetcher:main"

[tool.setuptools.packages.find]
where = ["src"]

[dependency-groups]
dev = [
    "ipython",
    "icecream"
]
